# Generated by Django 4.0.5 on 2022-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='tags',
        ),
        migrations.AddField(
            model_name='templates',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='HOME.temp_tag'),
        ),
    ]
