# Generated by Django 4.0.5 on 2022-07-08 00:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_alter_templates_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='templates',
            managers=[
                ('randoms', django.db.models.manager.Manager()),
            ],
        ),
    ]
