# Generated by Django 4.0.5 on 2022-07-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_alter_templates_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='templates',
            managers=[
            ],
        ),
    ]
