# Generated by Django 4.0.5 on 2022-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_rename_code_link_templates_css_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='html_head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='mobile_view',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
