# Generated by Django 4.0.5 on 2022-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0010_templates_html_head_templates_mobile_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='html_code',
            new_name='html_body',
        ),
    ]
